services:
  rag-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: agent-rag-streamlit:latest
    ports:
      - "8501:8501"
    environment:
      PYTHONUNBUFFERED: "1"
      AWS_REGION: "eu-west-1"
      BEDROCK_MODEL_ID: "qwen.qwen3-32b-instruct-v1:0"
    volumes:
      - ./.env:/app/.env:ro
